version: "1"
rules:                              # Array of rules
  - base: master                    # Required. Target branch
    upstream: ohmyzsh:master     # Required. Must be in the same fork network.
    mergeMethod: hardreset          # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
  - base: william_custom
    upstream: master                # Required. Can be a branch in the same forked repo.
    assignees:                      # Optional
      - kis87988
    reviewers:                      # Optional
      - kis87988
    mergeMethod: rebase
label: ":arrow_heading_down: pull"  # Optional
